### ISSUE TITLE
Editors on page stuck at 5px height and width.

### ISSUE THREAD

**Issue by cbj0** [serdarciplak/BlazorMonaco#36]
![image](https://user-images.githubusercontent.com/43776825/110482811-05244180-8124-11eb-861b-44ea356e0a00.png)

**Comment by cbj0** [comment]
HOW TO FIX THAT

**Comment by matt4446** [comment]
I had the same issue and resolved it with some css which probably isn't the intended solution.
 
CSS for the razor component that BlazorMonaco sits on
```CSS
::deep .monaco-editor-container {
    height: 500px;
}
```
